Factory/Models/Engineer.cs
using System;
using System.ComponentModel;
using System.Collections.Generic;

namespace Factory.Models
{
  public class Engineer
  {
    public Engineer()
    {
      this.JoinEntities = new HashSet<EngineerMachine>();
    }

    public int EngineerId { get; set; }
    [DisplayName("Name")]
    public string EngineerName { get; set; }
    public DateTime HireDate { get; set; }

    public virtual ICollection<EngineerMachine> JoinEntities { get;}
  }
}

Factory/Controllers/EngineersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using Factory.Models;


namespace Factory.Controllers
{
  public class EngineersController : Controller
  {

    private readonly FactoryContext _db;

    public EngineersController(FactoryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Engineers.ToList());
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Engineer engineer)
    {
      _db.Engineers.Add(engineer);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Details(int id)
    {
      var thisEngineer = _db.Engineers
        .Include(engineer => engineer.JoinEntities)
        .ThenInclude(join => join.Machine)
        .FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }

    public ActionResult Edit(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }

    [HttpPost]
    public ActionResult Edit (Engineer engineer)
    {
      _db.Entry(engineer).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddMachine (int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "MachineName");
      return View(thisEngineer);
    }

    [HttpPost]
    public ActionResult AddMachine(Engineer engineer, int MachineId)
    {
      if (MachineId != 0)
      {
        _db.EngineerMachine.Add(new EngineerMachine() { MachineId = MachineId, EngineerId = engineer.EngineerId });
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteMachine(int joinId)
    {
      var joinEntryE = _db.EngineerMachine.FirstOrDefault(entry => entry.EngineerMachineId == joinId);
      _db.EngineerMachine.Remove(joinEntryE);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      _db.Engineers.Remove(thisEngineer);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Factory/Views/Engineers/AddMachine.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Add a machine</h2>

<h4>Add a machine that this engineer is licensed to fix: @Html.DisplayFor(model => model.EngineerName)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.EngineerId)

  @Html.Label("Select Machine")
  @Html.DropDownList("MachineId")

  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to Engineers List", "Index")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

Factory/Views/Engineers/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h4>Add a new licensed Engineer</h4>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.EngineerName)
  @Html.TextBoxFor(model => model.EngineerName, new { required = "required"})
  <br />
  @Html.LabelFor(model => model.HireDate)
  @Html.TextBoxFor(model => model.HireDate, new { type = "date" })
  <br />
  <input type="submit" value="Add New Engineer" class="btn btn-default" />
}
<p>@Html.ActionLink("Show Engineers List", "Index")</p>

Factory/Views/Engineers/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Are you sure you want to remove this engineer?</h2>

@Html.DisplayNameFor(model => model.EngineerName): @Html.DisplayFor(model => model.EngineerName)
@using (Html.BeginForm())
{
  <input type="submit" value="Remove" />
}
<p>@Html.ActionLink("Back to Engineers List", "Index")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

Factory/Views/Engineers/Details.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Engineer Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.EngineerName): @Html.DisplayFor(model => model.EngineerName)</h3>
<h3>Date of Hire:
@Html.HiddenFor(model => model.EngineerId)
@Html.DisplayFor(model => model.HireDate.Month)/@Html.DisplayFor(model => model.HireDate.Day)/@Html.DisplayFor(model => model.HireDate.Year)</h3>
@if(@Model.JoinEntities.Count == 0)
{
  <p>This engineer isn't licensed to fix any machines yet.</p>
}
else
{
  <h4>Machines this engineer is licensed to fix: 
    <ul>
      @foreach(var join in Model.JoinEntities)
      {
        <li>@join.Machine.MachineName</li>
        @using (Html.BeginForm("DeleteMachine", "Engineers"))
        {
          @Html.Hidden("joinId", @join.EngineerMachineId)
          <input type="submit" value="Delete"/>
        }
      }
    </ul> 
  </h4>
}
<p>@Html.ActionLink("Back to Engineers List", "Index")</p>
<p>@Html.ActionLink("Edit Engineer", "Edit", new { id = Model.EngineerId })</p>
<p>@Html.ActionLink("Delete Engineer", "Delete", new { id = Model.EngineerId })</p>
<p>@Html.ActionLink("Add a Machine", "AddMachine", new { id = Model.EngineerId })</p>

Factory/Views/Engineers/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Edit</h2>

<h4>Edit this engineer: @Html.DisplayFor(model => model.EngineerName)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.EngineerId)

  @Html.LabelFor(model => model.EngineerName)
  @Html.EditorFor(model => model.EngineerName)
  <br />
  @Html.LabelFor(model => model.HireDate)
  @Html.TextBoxFor(model => model.HireDate, new { type = "date" })
  <br/>

  <input type="submit" value="Save" />
}
<p>@Html.ActionLink("Back to Engineers List", "Index")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

Factory/Views/Engineers/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models;
@model List<Factory.Models.Engineer>;

<div class="jumbotron">
  <h1>Engineers</h1>
</div>

@if (@Model.Count == 0)
{
  <h3> No engineers have been licensed yet!</h3>
}

@foreach (Engineer engineer in Model)
{
  <li>@Html.ActionLink($"{engineer.EngineerName}", "Details", new { id = engineer.EngineerId })</li>
}

<p>@Html.ActionLink("Add New Engineer", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>